# Generated by Django 5.0.2 on 2024-02-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fecha_mensaje',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
