# Generated by Django 5.0.2 on 2024-02-11 04:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_fecha_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mensaje',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
