# Generated by Django 5.0.2 on 2024-02-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imagen',
            field=models.ImageField(default='others/default_user.png', null=True, upload_to='users'),
        ),
    ]
