# Generated by Django 5.0.2 on 2024-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userprofile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link_web',
            field=models.TextField(blank=True, verbose_name='URL de Linkedln'),
        ),
    ]
